export const consejos = [
  '"El optimismo es la fe que conduce al logro. Nada se puede hacer sin esperanza y confianza". - Helen Keller',
  '"El secreto de la felicidad no es hacer siempre lo que se quiere, sino querer siempre lo que se hace". - León Tolstói',
  '"La felicidad no es la ausencia de problemas, es la habilidad para lidiar con ellos". - Steve Maraboli',
  '"La mayor parte de la felicidad depende de nuestra actitud y no de nuestras circunstancias". - Martha Washington',
  '"La gratitud puede transformar lo que tenemos en suficiente". - Anónimo',
  '"Cree en ti mismo y en todo lo que eres. No hay límites para lo que puedes lograr". - Maya Angelou',
  '"El éxito no es la clave de la felicidad. La felicidad es la clave del éxito. Si amas lo que haces, tendrás éxito". - Albert Schweitzer',
  '"El mayor descubrimiento de todos los tiempos es que una persona puede cambiar su futuro simplemente cambiando su actitud". - Oprah Winfrey',
  '"La felicidad es cuando lo que piensas, lo que dices y lo que haces están en armonía". - Mahatma Gandhi',
  '"No esperes que las cosas pasen, haz que sucedan". - Anónimo',
  '"Tu actitud determina tu dirección y tu éxito". - John C. Maxwell',
  '"El éxito es la suma de pequeños esfuerzos repetidos día tras día". - Robert Collier',
  '"Tus pensamientos positivos crean una vida positiva." - Anónimo',
  '"Tú eres el único responsable de tu propia felicidad." - Harvey Ball"',
  '"No dejes que el miedo te impida alcanzar tus sueños." - Anónimo',
  '"La gratitud transforma lo que tenemos en suficiente." - Anónimo',
  '"La confianza en ti mismo es el primer secreto del éxito". - Ralph Waldo Emerson',
  '"No importa cuántas veces caigas, lo importante es cuántas veces te levantes". - Vince Lombardi',
  '"La clave para alcanzar tus sueños es comenzar". - Mark Twain',
  '"Cree en ti mismo y en todo lo que eres. Sabes que hay algo dentro de ti que es más grande que cualquier obstáculo". - Christian D. Larson',
  '"Siempre parece imposible hasta que se hace". - Nelson Mandela',
  '"La disciplina es el puente entre metas y logros". - Jim Rohn',
  '"El verdadero éxito no se trata solo de alcanzar metas, sino de convertirse en la mejor versión de uno mismo en el proceso". - Anónimo',
  '"El fracaso es solo una oportunidad para comenzar de nuevo de manera más inteligente". - Henry Ford',
  '"El único límite para tus logros es tu imaginación". - Anónimo',
  '"No te compares con los demás. Compara tu hoy con tu ayer y trabaja para ser mejor cada día". - Anónimo',
  '"La vida es 10% lo que nos sucede y 90% cómo reaccionamos ante ello". - Charles R. Swindoll',
  '"El éxito no es la clave de la felicidad, la felicidad es la clave del éxito. Si amas lo que haces, serás exitoso". - Albert Schweitzer',
  '"No busques oportunidades extraordinarias, haz cosas ordinarias de manera extraordinaria". - Jim Rohn',
  '"El único camino hacia adelante es a través del esfuerzo y la determinación". - Colin Powell',
  '"El momento en que te sientes como rendirte, es el momento justo para seguir adelante". - Anónimo',
  '"Tu mayor limitación es tu propia mente. Rompe las barreras y cree en ti mismo". - Roy T. Bennett',
  '"El éxito es la suma de pequeños esfuerzos repetidos día tras día". - Robert Collier',
  '"No importa cuántas veces hayas fallado, levántate y sigue adelante. Tu perseverancia te llevará al éxito". - Unknown',
  '"El optimismo es la fe que conduce al logro. Nada se puede hacer sin esperanza y confianza". - Helen Keller',
  '"No permitas que tus miedos limiten tus sueños. Ve tras ellos con pasión y determinación". - Les Brown',
  '"La vida es como una bicicleta, para mantener el equilibrio debes seguir adelante". - Albert Einstein',
  '"No importa cuántas veces caigas, lo importante es levantarte una vez más con más fuerza". - Confucio',
  '"El éxito no se mide por la posición que has alcanzado en la vida, sino por los obstáculos que has superado en tu camino". - Booker T. Washington',
  '"El fracaso es una oportunidad para empezar de nuevo, pero de manera más inteligente". - Henry Ford',
  '"Las dificultades son oportunidades disfrazadas. No te rindas, encuentra la lección y sigue adelante". - Catherine Pulsifer',
  '"No importa cuán oscuro sea el camino, siempre hay una luz al final del túnel. Sigue adelante y encontrarás tu camino hacia la felicidad". - Anónimo',
  '"Tú eres el autor de tu propia historia. Si no te gusta cómo está y cómo va, escribe un nuevo capítulo". - Anónimo',
  '"La grandeza no proviene de lo que tienes, sino de lo que haces con lo que tienes". - Zig Ziglar',
  '"El secreto de salir adelante es comenzar. El secreto de comenzar es dividir tus tareas abrumadoras en tareas pequeñas y manejables, y luego comenzar por la primera". - Mark Twain',
  '"Nunca subestimes tu capacidad para sobreponerte. Eres más fuerte de lo que piensas y puedes superar cualquier desafío que se te presente". - Anónimo',
  '"La clave para el éxito es enfocarse en tus metas, no en los obstáculos". - Anónimo',
  '"No permitas que el pasado defina tu futuro. Cada día es una nueva oportunidad para cambiar tu vida". - Anónimo',
  '"El éxito no es la clave de la felicidad, la felicidad es la clave del éxito. Si amas lo que haces, serás exitoso". - Albert Schweitzer',
  '"El momento en que piensas en rendirte, recuerda por qué empezaste". - Anónimo',
  '"La vida te pondrá obstáculos, pero los límites los pones tú. Supera tus propias barreras y alcanza nuevas alturas". - Anónimo',
  '"No esperes a que llegue el momento perfecto; toma el momento y hazlo perfecto". - Unknown',
  '"El éxito no se mide por la cantidad de dinero que tienes, sino por el impacto positivo que haces en la vida de los demás". - Zig Ziglar',
  '"Cuando sientas que todo está en tu contra, recuerda que el avión despega contra el viento, no a favor". - Henry Ford',
  '"No temas al fracaso, teme a no intentarlo". - Roy T. Bennett',
  '"Tu mayor competencia eres tú mismo. Supérate a ti mismo cada día y estarás en el camino hacia el éxito". - Anónimo',
];
export const consejosfavorito = [];
